# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The World According to Marc
header-img: img/home-bg.jpg
email: marc@massivescale.com
copyright_name: Marc LaFleur
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://massivescale.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mlafleur
github_username:  mlafleur
#email_username:  marc@massivescale.com
google_tracking_id: UA-3085958-5
linkedin_username: marclafleur
facebook_username: mlafleurMSFT

# Build settings
markdown: kramdown
highlighter: rouge
#theme: jekyll-theme-slate
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
permalink: /:categories/:title/
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","archive"]